import Image from 'next/image';
import Link from 'next/link';
import { ArrowRight, Clock, MapPin, MessageCircle } from 'lucide-react';
import { StoreLocationMap } from '@/components/shared/StoreLocationMap';

export default function SobrePage() {
  return <div className="jk-paper-grid min-h-screen">
    <section className="mx-auto grid max-w-7xl lg:grid-cols-[.9fr_1.1fr] lg:items-stretch"><div className="jk-reveal flex flex-col justify-center px-4 py-14 sm:px-6 sm:py-20 lg:px-8"><p className="text-xs font-black uppercase tracking-[.2em] text-[#b4232d]">A JK Copycenter</p><h1 className="jk-display mt-4 text-5xl font-black leading-none text-[#092653] sm:text-6xl">Uma gráfica e papelaria no caminho de quem vive Passos.</h1><p className="mt-6 text-lg leading-8 text-slate-600">O site organiza a solicitação; o atendimento continua humano. Você envia o material, a equipe analisa e o orçamento fica registrado antes de qualquer cobrança.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link href="/grafica" className="inline-flex min-h-12 items-center justify-center gap-2 rounded-full bg-[#092653] px-6 font-black text-white">Pedir análise <ArrowRight className="h-4 w-4" /></Link><a href="https://wa.me/5535991066260" target="_blank" rel="noopener noreferrer" className="inline-flex min-h-12 items-center justify-center gap-2 rounded-full border border-[#092653]/25 bg-[#fffdf8] px-6 font-black text-[#092653]"><MessageCircle className="h-5 w-5" />WhatsApp</a></div></div><div className="relative min-h-[420px] overflow-hidden lg:min-h-[650px]"><Image src="/images/brand/jk-fachada-1440.webp" alt="Fachada da JK Copycenter na Avenida JK em Passos" fill sizes="(min-width:1024px) 55vw, 100vw" className="object-cover object-center" priority /></div></section>

    <section className="border-y border-[#092653]/10 bg-[#fffdf8]"><div className="mx-auto grid max-w-7xl gap-8 px-4 py-14 sm:px-6 md:grid-cols-3 lg:px-8"><div><MapPin className="h-6 w-6 text-[#b4232d]" /><h2 className="mt-4 text-lg font-black text-[#092653]">Onde estamos</h2><p className="mt-2 text-sm leading-6 text-slate-600">Av. JK, 270<br />Jardim Colégio de Passos<br />Passos/MG · 37901-000</p></div><div><Clock className="h-6 w-6 text-[#b4232d]" /><h2 className="mt-4 text-lg font-black text-[#092653]">Horários informados</h2><p className="mt-2 text-sm leading-6 text-slate-600">Segunda a sexta, 09h às 18h<br />Sábado, 09h às 12h</p></div><div><MessageCircle className="h-6 w-6 text-[#b4232d]" /><h2 className="mt-4 text-lg font-black text-[#092653]">Fale com a loja</h2><p className="mt-2 text-sm leading-6 text-slate-600">WhatsApp: (35) 99106-6260<br />Instagram: @jkcopycenter<br />Facebook: JKCopyCenter</p></div></div></section>

    <section className="mx-auto max-w-7xl px-4 py-16 sm:px-6 lg:px-8"><div className="mb-8"><p className="text-xs font-black uppercase tracking-[.2em] text-[#b4232d]">Visite a unidade</p><h2 className="jk-display mt-3 text-4xl font-black text-[#092653]">Rota e referência</h2></div><StoreLocationMap /></section>
  </div>;
}
